name: Kulectiv
favicon: null
layout_spectrum: 0.5853013216983527
typography_spectrum: 0.12519885203801095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff8600'
    - '#ffc878'
    - '#515151'
    - '#7b7b7b'
  brandStrength: 0.48754833173006773
  lightness: 0.2646995878312737
  saturation: 0.5708097533788532
  rhythmicContrast: 0.6109142440836877
purpose: []
